### ISSUE TITLE
移除 ~/.config/fontconfig 目录后 fontweak 启动不起来了。

### ISSUE THREAD

**Issue by bruceauyeung** [guoyunhe/font-config-master#28]
后台报NPE异常

```
一月 13, 2016 8:33:28 下午 me.guoyunhe.fontweak.FontConfigXML readConfig
严重: null
java.io.FileNotFoundException: /home/bruce/.config/fontconfig/fonts.conf (没有那个文件或目录)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
        at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:622)
        at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:189)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:812)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:348)
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
        at me.guoyunhe.fontweak.FontConfigXML.readConfig(FontConfigXML.java:152)
        at me.guoyunhe.fontweak.FontConfigXML.readConfig(FontConfigXML.java:185)
        at me.guoyunhe.fontweak.MainWindow.initApplication(MainWindow.java:904)
        at me.guoyunhe.fontweak.MainWindow.<init>(MainWindow.java:62)
        at me.guoyunhe.fontweak.MainWindow$14.run(MainWindow.java:881)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)                                                                                        
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)                                                                                     
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)                                                                                                 
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)                                                                                                  
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)                                                                                                         

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException                                                                                                            
        at me.guoyunhe.fontweak.FontConfigXML.readConfig(FontConfigXML.java:160)                                                                                                 
        at me.guoyunhe.fontweak.FontConfigXML.readConfig(FontConfigXML.java:185)                                                                                                 
        at me.guoyunhe.fontweak.MainWindow.initApplication(MainWindow.java:904)                                                                                                  
        at me.guoyunhe.fontweak.MainWindow.<init>(MainWindow.java:62)                                                                                                            
        at me.guoyunhe.fontweak.MainWindow$14.run(MainWindow.java:881)                                                                                                           
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)                                                                                                     
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)                                                                                                            
        at java.awt.EventQueue.access$500(EventQueue.java:97)                                                                                                                    
        at java.awt.EventQueue$3.run(EventQueue.java:709)                                                                                                                        
        at java.awt.EventQueue$3.run(EventQueue.java:703)                                                                                                                        
        at java.security.AccessController.doPrivileged(Native Method)                                                                                                            
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)                                                               
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by guoyunhe** [comment]
这个是个已知的 bug 了。

**Comment by guoyunhe** [comment]
See #26
